language: rust
# We use OSX so that we can get a reasonably up to date version of SQLCipher.
# (The version in Travis's default Ubuntu Trusty is much too old).
os: osx
before_install:
  - brew install sqlcipher --with-fts
rust:
  - 1.25.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
jobs:
  include:
    - stage: "Test iOS"
      rust: 1.25.0
      script: ./scripts/test-ios.sh
    - stage: deploy
      if: branch = master
      rust: 1.25.0
      script: ./scripts/build-doc.sh
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        local-dir: docs/apis/latest
        target-branch: gh-pages-api-docs
        verbose: true
        on:
          branch: master
script:
  - cargo test --verbose --all
  - cargo test --features edn/serde_support --verbose --all
  # We can't pick individual features out with `cargo test --all` (At the time of this writing, this
  # works but does the wrong thing because of a bug in cargo, but its fix will be to disallow doing
  # this all-together, see https://github.com/rust-lang/cargo/issues/5364 for more information). To
  # work around this, we run tests individually for subcrates that rely on `rusqlite`.
  - |
    for crate in "" "db" "db-traits" "ffi" "public-traits" "query-projector" "query-projector-traits" "query-pull" "sql" "tolstoy" "tolstoy-traits" "transaction" "tools/cli"; do
      cargo test --manifest-path ./$crate/Cargo.toml --verbose --no-default-features --features sqlcipher
    done
cache: cargo
