language: rust
rust:
  - 1.25.0  # Must align with `build/version.rs`.
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - cargo test --verbose --all
cache: cargo
