[package]
authors = ["Richard Newman <rnewman@twinql.com>", "Nicholas Alexander <nalexander@mozilla.com>"]
name = "mentat"
version = "0.4.0"

[dependencies]
clap = "2.19.3"
rusqlite = "0.8.0"
slog = "1.4.0"
slog-scope = "0.2.2"
slog-term = "1.3.4"

[dependencies.edn]
path = "edn"

[dependencies.mentat_query]
path = "query"

[dependencies.mentat_query_parser]
path = "query-parser"
