[package]
authors = ["Richard Newman <rnewman@twinql.com>", "Nicholas Alexander <nalexander@mozilla.com>"]
name = "mentat"
version = "0.4.0"

[dependencies]
clap = "2.19.3"
nickel = "0.9.0"
slog = "1.4.0"
slog-scope = "0.2.2"
slog-term = "1.3.4"
time = "0.1.35"

[dependencies.rusqlite]
version = "0.9.5"
# System sqlite might be very old.
features = ["bundled"]

[dependencies.edn]
path = "edn"

[dependencies.mentat_parser_utils]
path = "parser-utils"

[dependencies.mentat_core]
path = "core"

[dependencies.mentat_db]
path = "db"

[dependencies.mentat_query]
path = "query"

[dependencies.mentat_query_parser]
path = "query-parser"

[dependencies.mentat_tx_parser]
path = "tx-parser"
