[package]
name = "mentat_query_projector"
version = "0.0.1"
workspace = ".."

[dependencies]
error-chain = "0.8.1"

[dependencies.rusqlite]
version = "0.10.1"
# System sqlite might be very old.
features = ["bundled", "limits"]

[dependencies.mentat_core]
path = "../core"

[dependencies.mentat_db]
path = "../db"

[dependencies.mentat_sql]
path = "../sql"

[dependencies.mentat_query]
path = "../query"

[dependencies.mentat_query_algebrizer]
path = "../query-algebrizer"

# Only for tests.
[dev-dependencies.mentat_query_parser]
path = "../query-parser"

[dependencies.mentat_query_sql]
path = "../query-sql"

