[package]
name = "mentat_query_algebrizer"
version = "0.0.1"
workspace = ".."

[dependencies]
error-chain = "0.9.0"

[dependencies.mentat_core]
path = "../core"

[dependencies.mentat_query]
path = "../query"

# Only for tests.
[dev-dependencies.mentat_query_parser]
path = "../query-parser"