[package]
name = "mentat_db"
version = "0.0.1"

[dependencies]
error-chain = "0.8.0"
lazy_static = "0.2.2"
# TODO: don't depend on num and ordered-float; expose helpers in edn abstracting necessary constructors.
num = "0.1.35"
ordered-float = "0.4.0"

[dependencies.rusqlite]
version = "0.9.3"
# System sqlite might be very old.
features = ["bundled"]

[dependencies.edn]
path = "../edn"

[dependencies.mentat_tx]
path = "../tx"

[dependencies.mentat_tx_parser]
path = "../tx-parser"
