[package]
name = "mentat_query_parser"
version = "0.0.1"

[dependencies]
combine = "2.1.1"
matches = "0.1"

[dependencies.edn]
  path = "../edn"

[dependencies.mentat_parser_utils]
  path = "../parser-utils"

[dependencies.mentat_query]
  path = "../query"
