[package]
name = "mentat_tx_parser"
version = "0.0.1"
workspace = ".."

[dependencies]
combine = "2.1.1"

[dependencies.edn]
  path = "../edn"

[dependencies.mentat_tx]
  path = "../tx"

[dependencies.mentat_parser_utils]
  path = "../parser-utils"
