# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Mentat
description: >- # this means to ignore newlines until "baseurl:"
  Project Mentat is a persistent, embedded knowledge base. It draws heavily on DataScript and Datomic.
  Mentat is intended to be a flexible relational (not key-value, not document-oriented) store that makes
  it easy to describe, grow, and reuse your domain schema.
baseurl: /mentat # the subpath of your site, e.g. /blog
url: https://mozilla.github.io # the base hostname & protocol for your site, e.g. http://example.com

api_heading: API Documentation
list_title: Examples

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
